apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aster-license-signing-api.fullname" . }}-audit
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.audit.storage | quote }}
