apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: license-signing-api-audit
  namespace: aster-license-signing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
