apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: license-signing-api
  namespace: aster-license-signing
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: license-signing-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
